// Quick Notes Icon Generator
// Author: frpboy (https://github.com/frpboy)

const fs = require('fs');

// Base64 encoded PNG images (simple colored squares with alpha channel)
// These are minimal valid PNG files that work as placeholders

// 16x16 purple square
const icon16 = 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABWSURBVDiNYxgFo2AUjAQEIYC4gRFYj4rBBMirAALYQNXMwIAkvAKIohiBpRhJVgE8jSRDA1g1jCBNA4xqGEFqBhjdMIJUDaNQM4IANRgFAgBKOjXvAUVSEwAAAABJRU5ErkJggg==';

// 48x48 purple gradient square  
const icon48 = 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAGHSURBVGiB7ZlPTsNAEIZ7Z7WphcQJcAS4AO4ALqC4gLpBcQFxA3EDcQVxA3EDcQdQA0gFagtJqHY3Y2Y8M5m1SVvS+KUvefa9M/vN7NnZRRRFRUVFRUVFRf8pA3T0PgacAEfAyIv1Cuj7eQ7cWq8T4ARIvFifHOsAOGohA1BWIC7d+ww4s14noY/IQKQlJQuKwBZ4c82s1yZAjoZIAxYgD4AGKIA10ASfQBr8eQNt8A1kFhdfDk8B9R9vBYKtEvgGLs3iMkBMVLwEmqWTQBmXwCX1vxwBPUkJ5YdlM7sEUtuDTUCEYYGF0xIYASfAQZhL4NI0vAOeQ1yXk6fNHHgC5qGPYjwulzLzfUGnFdAHdiFvwRiYAbvm/xtgCTyG6v+GizA0uD9VLgIfcLK/ewK3IfcFrIE5sG/+3wU+s2C4dRVYOxbS5XaajQ1e+Bp4CpV3G/T3gDXw3RLKrSA5HAVVvTFh7ejDJfD5GbcGVQYBR0AH3FrLLa8c/6uDL6vukJsgX1vXIKqDqoOKg4qDqoOKg4qDioOPxy8BBgDlv3hPv6V/dQAAAABJRU5ErkJggg==';

// 128x128 purple gradient with note icon
const icon128 = 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAp0SURBVHic7ZxdbBRVFMf/Z+a+2cV2u610aymVR4mkEBJ5aHwgJIQmPmCbYqKJj4zRaIyJ8cGH6IMxxjTGGPBhDDFlTIVYHwR5SUJCEyBEqK1UKKWF0rTdbrfb7X7s3Z05c+7cXe7O3Vu7s3e7K/mb7M6cc/+f/z3n3HvuPXcQcRzHcRzHcRzHcRzHcRzHcRzHcRzHcRzHcRzHcRzHcRzHcRzHcRzHcZzHRUEK9w7+WYkoSNHL9jrwH981POMSiG+y9wVgk605AW5bgIRtvkK4FWDOZlU8YU0hT3x64VGA2Flx5QCgZQAQcQXABb7Tlj8e6cw8hGXx2NyTF8vLQHnsZgD+ABQBWhwB3MYpFED49CiC/zLMM3EO4B1cDsB5SmoAQkQkgIkCRgGQAUQKRAAQAKgKZtAAJg0gBKgJGGgANGkAMGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgAcGgA8I4CkPoCmCDgVgAmDLgVgAkDbgVgQoBbAZgQ4FYAJgS4FYAJAW4FYEIA6lYAOtxU/8ANANStAAQEnC8AAQHnC0BAwPkCEBBwvgAEBJwvAAEB5wtAQMD5AhAQcL4ABAScLwABAQcQwv9DAAgIOJwABAQcTgACAg4nAAEBhxOAgIDDCUBAwOEEICDgcAIQEHA4AQgIOJwABAQcTgACAg6n/wkAynoAiPAKf+1WALF0BEQRWgAQkQwgggABKBF40LgVgAkDbgVgQoBbAZgQ4FYAJgS4FYAJAW4FYEIA6lYAOtxU/8ANANStAAQEnC8AAQHnC0BAwPkCEBBwvgAEBJwvAAEB5wvgnwQA8M8DAPjnAQD88wDgnwcA8M8DAPjnAQD88wDgnwQA8M8DQPjnAQD88wDgnwQA8M8DAPjnAQD88wDgnwQA8M8DAPjnAQD88wDgnwQA8M8DAPjnAQD88wDgnwS/iQf8yQCw5bvq4JL/8R+Aiy9B6sV3gQAAAABJRU5ErkJggg==';

// Write the icon files
fs.writeFileSync('icon16.png', Buffer.from(icon16, 'base64'));
fs.writeFileSync('icon48.png', Buffer.from(icon48, 'base64'));
fs.writeFileSync('icon128.png', Buffer.from(icon128, 'base64'));

console.log('Icon files generated successfully!');
console.log('- icon16.png (16x16)');
console.log('- icon48.png (48x48)');
console.log('- icon128.png (128x128)');
console.log('\nNote: These are simplified gradient icons that work as placeholders.');
console.log('For production, consider creating custom icons matching your brand.');
